name = "0x5eal/unzip"
version = "0.1.0"
description = "unzip implementation in pure Luau"
authors = ["Erica Marigold <hi@devcomp.xyz>"]
repository = "https://github.com/0x5eal/luau-unzip"
license = "MIT"

[target]
environment = "luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
pathfs = { name = "jiwonz/pathfs", version = "^0.1.0", target = "lune" }
