name = "0x5eal/unzip"
version = "0.1.3"
description = "Unzip implementation in pure Luau"
authors = ["Erica Marigold <hi@devcomp.xyz>"]
repository = "https://github.com/0x5eal/luau-unzip"
license = "MIT"
includes = [
	"README.md",
	"LICENSE.md",
	"pesde.toml",
	"lib/**/*.luau",
	"!tests/**/*",
  	"docs/**/*.md"
]

[engines]
pesde = "^0.7.0"

[scripts]
tests = ".lune/tests/init.luau"
fmt = ".lune/fmt.luau"
typecheck = ".lune/typecheck.luau"
generate_invalid_version_zip = "scripts/generate_invalid_version_zip.luau"

[target]
environment = "luau"
lib = "lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
stylua = { name = "pesde/stylua", version = "=2.1.0", target = "lune" }
frktest = { name = "abidbmt/frktest", version = "^0.1.1", target = "lune" }
asciitable = { name = "kimpure/asciitable", version = "^0.2.2" }
luau-lsp = { name = "pesde/luau_lsp", version = "=1.53.2", target = "lune" }
