name = "0x5eal/unzip"
version = "0.0.1"
description = "Unzip implementation in pure Luau"
authors = ["Erica Marigold <hi@devcomp.xyz>"]
repository = "https://github.com/0x5eal/luau-unzip"
license = "MIT"
includes = [
	"README.md",
	"LICENSE.md",
	"pesde.toml",
	"lib/**/*.luau",
	"!tests/**/*",
]

[target]
environment = "luau"
lib = "lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
stylua = { name = "pesde/stylua", version = "^2.0.2", target = "lune" }
frktest = { name = "itsfrank/frktest", version = "^0.0.2", target = "lune" }
asciitable = { name = "kimpure/asciitable", version = "^0.1.4" }
